```ini
[webservers]
web_node_01 ansible_host=54.210.43.12 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/aws-deploy.pem

[dbservers]
db_node_01 ansible_host=54.210.43.99 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/aws-deploy.pem

[mern:children]
webservers
dbservers
```