[webservers]
web_node_01 ansible_host=40.114.25.163 ansible_ssh_private_key_file=~/multicloud-key/ssh-key-rg.pem

[dbservers]
db_node_01 ansible_host=10.0.2.4 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q azureuser@40.114.25.163 -i ~/multicloud-key/ssh-key-rg.pem"' ansible_ssh_private_key_file=~/multicloud-key/ssh-key-rg.pem

[mern:children]
webservers
dbservers