---
- name: Apply Base OS Hardening to All Target Hosts
  hosts: mern
  become: true
  roles:
    - common

- name: Provision and Secure Database Topology
  hosts: dbservers
  become: true
  roles:
    - dbserver

- name: Provision, Build and Daemonize Web Tier
  hosts: webservers
  become: true
  roles:
    - webserver