---
- name: Apply common configurations to all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Setup and configure MongoDB database nodes
  hosts: dbservers
  become: true
  roles:
    - dbserver

- name: Deploy application environment to web nodes
  hosts: webservers
  become: true
  roles:
    - webserver